//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public int idParent { get; set; }
        public string nomParent { get; set; }
        public string prenomParent { get; set; }
        public string adresseParent { get; set; }
        public string villeParent { get; set; }
        public string provinceParent { get; set; }
        public string cpParent { get; set; }
        public string noTelParent { get; set; }
        public int refPatient { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
